dist: xenial

language: python

addons:
  apt:
    packages:
      - libev-dev

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: pypy
      env: TOX_ENV=pypy
    - python: pypy3.5
      env: TOX_ENV=pypy35
    - python: 3.7
      env: TOX_ENV=docs
    - python: 3.7
      env: TOX_ENV=flake8

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi"
